"""Prompt library. Documented in docs/PROMPT_LIBRARY.md."""

from agents.prompts.system import (
    DIAGNOSTIC_BACKSTORY,
    ESCALATION_BACKSTORY,
    REPORTING_BACKSTORY,
    RESEARCH_BACKSTORY,
    RESOLUTION_BACKSTORY,
    SHARED_RULES,
    TRIAGE_BACKSTORY,
    VALIDATION_BACKSTORY,
)
from agents.prompts.task import (
    DIAGNOSTIC_TASK,
    ESCALATION_TASK,
    REPORTING_TASK,
    RESEARCH_TASK,
    RESOLUTION_TASK,
    ROUTING_TASK,
    TRIAGE_TASK,
    VALIDATION_TASK,
)

__all__ = [
    "SHARED_RULES",
    "TRIAGE_BACKSTORY",
    "RESEARCH_BACKSTORY",
    "DIAGNOSTIC_BACKSTORY",
    "RESOLUTION_BACKSTORY",
    "VALIDATION_BACKSTORY",
    "ESCALATION_BACKSTORY",
    "REPORTING_BACKSTORY",
    "TRIAGE_TASK",
    "ROUTING_TASK",
    "RESEARCH_TASK",
    "DIAGNOSTIC_TASK",
    "RESOLUTION_TASK",
    "VALIDATION_TASK",
    "ESCALATION_TASK",
    "REPORTING_TASK",
]
