name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the backend Docker image
        run: docker build . --file backend/Dockerfile --tag supportops-backend:$(date +%s)
      - name: Build the frontend Docker image
        run: docker build ./frontend --file frontend/Dockerfile --tag supportops-frontend:$(date +%s)
